<?php

namespace VectorXHD\TrophyBundle\Repository;
use VectorXHD\TrophyBundle\Entity\BadgeUnlock;

/**
 * BadgeUnlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeUnlockRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param BadgeUnlock $badgeUnlock
     */
    public function save(BadgeUnlock $badgeUnlock)
    {
        $this->_em->persist($badgeUnlock);
        $this->_em->flush();
    }
}
